{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error checking enrollment: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist","service":"user-service","sql":"SELECT * FROM AuthFlowUsers WHERE email = 'authflowauthenticator@gmail.com'","sqlMessage":"Table 'accounts.AuthFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at D:\\ClientSide2.0\\server.js:488:16\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2024-04-10T21:36:39.357Z"}
{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error when setting all users to logged out: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist","service":"user-service","sql":"UPDATE AuthFlowUsers SET is_logged_in = FALSE","sqlMessage":"Table 'accounts.AuthFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at D:\\ClientSide2.0\\server.js:215:16\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2024-04-10T21:36:39.459Z"}
{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error when setting user to logged in: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist","service":"user-service","sql":"UPDATE AuthFlowUsers SET is_logged_in = TRUE WHERE email = 'authflowauthenticator@gmail.com'","sqlMessage":"Table 'accounts.AuthFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:222:18)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:92:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)","timestamp":"2024-04-10T21:36:39.561Z"}
{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error checking enrollment: ER_NO_SUCH_TABLE: Table 'accounts.authFlowUsers' doesn't exist","service":"user-service","sql":"SELECT * FROM authFlowUsers WHERE email = 'authflowauthenticator@gmail.com'","sqlMessage":"Table 'accounts.authFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.authFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at D:\\ClientSide2.0\\server.js:323:16\n    at Request._callback (D:\\ClientSide2.0\\server.js:293:7)\n    at self.callback (D:\\ClientSide2.0\\node_modules\\request\\request.js:185:22)\n    at Request.emit (node:events:518:28)\n    at Request.emit (node:domain:488:12)\n    at Request.<anonymous> (D:\\ClientSide2.0\\node_modules\\request\\request.js:1154:10)\n    at Request.emit (node:events:518:28)\n    at Request.emit (node:domain:488:12)","timestamp":"2024-04-10T21:36:51.542Z"}
{"level":"error","message":null,"service":"user-service","timestamp":"2024-04-10T21:37:07.622Z"}
{"level":"error","message":null,"service":"user-service","timestamp":"2024-04-10T21:37:37.514Z"}
{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error when setting all users to logged out: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist","service":"user-service","sql":"UPDATE AuthFlowUsers SET is_logged_in = FALSE","sqlMessage":"Table 'accounts.AuthFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at D:\\ClientSide2.0\\server.js:215:16\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2024-04-10T21:54:04.830Z"}
{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error when setting user to logged in: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist","service":"user-service","sql":"UPDATE AuthFlowUsers SET is_logged_in = TRUE WHERE email = 'authflowauthenticator@gmail.com'","sqlMessage":"Table 'accounts.AuthFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:222:18)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:92:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)","timestamp":"2024-04-10T21:54:04.931Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('authflowauthenticator@gmail.com', 'ad5e09530b6d06d1b930813b4961a5a0115209b3135654705781d02852679fed', '58851113', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-10T21:54:19.371Z"}
{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error when setting all users to logged out: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist","service":"user-service","sql":"UPDATE AuthFlowUsers SET is_logged_in = FALSE","sqlMessage":"Table 'accounts.AuthFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at D:\\ClientSide2.0\\server.js:215:16\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (D:\\ClientSide2.0\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2024-04-10T21:59:20.516Z"}
{"code":"ER_NO_SUCH_TABLE","errno":1146,"index":0,"level":"error","message":"Database error when setting user to logged in: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist","service":"user-service","sql":"UPDATE AuthFlowUsers SET is_logged_in = TRUE WHERE email = 'authflowauthenticator@gmail.com'","sqlMessage":"Table 'accounts.AuthFlowUsers' doesn't exist","sqlState":"42S02","stack":"Error: ER_NO_SUCH_TABLE: Table 'accounts.AuthFlowUsers' doesn't exist\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:222:18)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:92:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)","timestamp":"2024-04-10T21:59:20.641Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('authflowauthenticator@gmail.com', '4634b2ac9cc2cc94fa50f5f92a2d6ae2e0c1a6af68da7c2881d6022cf40d1ee4', '94418706', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-10T21:59:37.744Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('bhattnaman141@gmail.com', '8ed66c539790141a1a2556c6bb61aece77e53556b5e70b42e7fb67465f4a95be', '15323278', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-10T22:08:46.524Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('bhattnaman481@gmail.com', 'c0ae386387b1649c05eb748436214f8be23b5494eef896a6e17b72ca275168b3', '23789864', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-10T22:09:09.358Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('bhattnaman481@gmail.com', '464258d78425f35b52f4c1cc6abd762564c74d47717469f21ea1cb1cb61b7e9c', '82953538', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-10T22:22:18.481Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('bhattnaman481@gmail.com', 'e96470241d87b5a245b491dd3da084edaa57dfd8884d911ef9e1731c79054124', '24887629', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-11T00:47:07.429Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('bhattnaman481@gmail.com', '7d5ffd071747720de9d80058dfde71d7123470b8580f6a87ab08ab4a46461e87', '61278884', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-11T00:47:25.586Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('bhattnaman481@gmail.com', 'b57f383506f4ff7c546b23137e5051a751a621c69848e4ee57925d42699d152e', '52260636', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-11T04:05:09.308Z"}
{"code":"ER_NO_DEFAULT_FOR_FIELD","errno":1364,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, idp) VALUES ('bhattnaman481@gmail.com', 'e9fea08d0b42a6409d42377e493fc636819d68ab3091f89f676ba8baa8b1df33', '31743237', 1, 'google-oauth2')","sqlMessage":"Field 'is_logged_in' doesn't have a default value","sqlState":"HY000","stack":"Error: ER_NO_DEFAULT_FOR_FIELD: Field 'is_logged_in' doesn't have a default value\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-11T04:06:08.449Z"}
{"code":"ER_PARSE_ERROR","errno":1064,"index":0,"level":"error","message":"Error enrolling user in AuthFlow Authenticator: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1","service":"user-service","sql":"INSERT INTO authflowusers (email, password_hash, pin, is_enrolled, is_logged_in, idp) VALUES ('bhattnaman481@gmail.com', 'f288c93a23ceb79b37400dbdc24d37e213d27f26fdea454232153e777974682c', '13826749', 1,'google-oauth2', ?)","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1","sqlState":"42000","stack":"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1\n    at Sequence._packetToError (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:47:14)\n    at Query.ErrorPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:79:18)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:88:28)\n    at Socket.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Socket.emit (node:events:518:28)\n    at Socket.emit (node:domain:488:12)\n    --------------------\n    at Protocol._enqueue (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:144:48)\n    at Connection.query (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:198:25)\n    at Query.<anonymous> (D:\\ClientSide2.0\\server.js:421:20)\n    at Query.<anonymous> (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:526:10)\n    at Query._callback (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\Connection.js:488:16)\n    at Sequence.end (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query._handleFinalResultPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:149:8)\n    at Query.EofPacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:133:8)\n    at Protocol._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (D:\\ClientSide2.0\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)","timestamp":"2024-04-11T04:07:16.546Z"}
